name: Release Workflow

on: workflow_dispatch

jobs:
  release:
    name: Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Step
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js Step
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies Step
        run: yarn install

      - name: Lint Step
        run: yarn lint

      - name: Test Step
        run: yarn test:ci

      - name: Build Step
        run: yarn build:all:prod

      - name: Release Step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
