name: Setup Environment Workflow

jobs:
  setup-env:
    name: Setup Environment Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Step
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js Step
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies Step
        run: yarn install
