name: Test and Build Workflow

on: [ push, pull_request ]

jobs:
  test-build:
    name: Test and Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Step
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js Step
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'yarn'

      - name: Install Dependencies Step
        run: yarn install

      - name: Lint Step
        run: yarn lint

      - name: Test Step
        run: yarn test:ci

      - name: Build Step
        run: yarn build:all:prod
